### ISSUE TITLE
How do I know which version of the Windows app I have? 

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.gui#1]
* Windows 10 with Pocketnet app 0.0.14.

I have not yet found the version of the Windows app in the actual Windows app. This will be needed for tech support. Can you add this somewhere? Perhaps on the main profile screen. 

By sheer guessing and looking at Github, it looks like I have v0.0.14 beta as Pocketnet updated soon after I installed it.

**Comment by pocketnetteam** [comment]
Thanks for your feedback.

We added the current version to the window title in commit https://github.com/pocketnetteam/pocketnet.gui/commit/0dddf507dfb430bd4607a0b85860755d30a64783
