### ISSUE TITLE
When posting, there are no tooltips on these 3 icons at the bottom

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.gui#10]
* Windows 7 using Pocketnet via Firefox v66.0.2

Since there are no tooltips on these icons I have no idea what they do. Can you add tooltips to these? 

Image is here: <https://i.ibb.co/zrg9Rws/pocketnet-tooltips.png>

**Comment by shpingalet007** [comment]
Checked on Firefox 100.0.2. Is this still actual @bulrush15? Consider reopening this issue if it is. I assume that is resolved. Thanks for your interest in Bastyon!
