### ISSUE TITLE
8.53 shows only Title in Node

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#1074]
### Describe the bug

After installing 8.53 while attempting to download the DB, nothing shows but the title on the node page. This was true after uninstalling and reinstalling 8.53.

I finally uninstalled 8.53 and reinstalled 8.51 and all the option on the node page came back and am now downloading the data at an agonizingly slow 355kbs/s 

### Steps to reproduce

install 8.53

### Expected behavior

I should be able to begin downloading the node and data again.

### OS / Linux distribution

Win 11

### Version

v08.53

### Type application

Desktop

**Comment by shpingalet007** [comment]
Thanks for your report! The bug is located and will be fixed tomorrow. There was several reports on this issue so will be done urgently.
