### ISSUE TITLE
snapshot.pocketnet.app slow downloads

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#1075]
355k/s for a 40GB file...do you see the problem? it's two days out of date if it doesn't bork itself downloading.

Any chance of getting it back to 1.8MB/s like it used to be?

**Comment by andyoknen** [comment]
@graebeerd What ping do you have to the snapshot.pocketnet.app server?

**Comment by graebeerd** [comment]
Reply from 178.217.159.221: bytes=32 time=183ms TTL=41
Reply from 178.217.159.221: bytes=32 time=187ms TTL=41
Reply from 178.217.159.221: bytes=32 time=184ms TTL=41
Reply from 178.217.159.221: bytes=32 time=188ms TTL=41

**Comment by andyoknen** [comment]
It seems there are no problems in the middle, at least no obvious problems. Maybe this is due to the daily load of the server? Although I can't say that this server is powerful in terms of an Internet channel

**Comment by graebeerd** [comment]
I've tried it (I'm at -5) at nearly midnight, middle of the day, early in the morning with both FF and Edge with both hovering around 320kb/s. I can easily dl at ~2 MB/s (I have a gb pipe) at most other sites and well over 4MB/s on torrents. I've completely given up running an easy node as despite clearing/deleting the node, it never successfully downloads the db.

**Comment by andyoknen** [comment]
If you have a regular node with a loaded blockchain, you can use it in a simple node..

**Comment by graebeerd** [comment]
Whatever was done has fixed the DL speed as I get >5MB/S now and have for the last few times I've tried. 

However, currently the the snapshot is over 2 weeks old and although installed fine on the Win GUI, it hangs and stops with only about an hour to go.

Once I can get a current snapshot (or more current) I'll close this ticket.

**Comment by andyoknen** [comment]
Snapshot for height 2452237 updated.
