### ISSUE TITLE
RSS feeds for the web interface

### ISSUE THREAD

**Issue by jcalfee** [pocketnetteam/pocketnet.gui#13]
You have great content but users are more spread out on different social media sites these days so it becomes hard to keep up with.  It is nice that the email is not linked to user names, but that also means users will not have any notifications.  If there were an RSS feed to any user's content or even their subscribed feeds, we could then monitor our own feed or could even monitor someone else's feed or channel.

**Comment by andysavage** [comment]
Yes RSS would be a great addition.

**Comment by reignmen** [comment]
You guys must be missing the point of open source

**Comment by andysavage** [comment]
> You guys must be missing the point of open source
Or you are missing the point of having some people be software developers and others do things like produce food, etc.

**Comment by shpingalet007** [comment]
Not planned, closing
