### ISSUE TITLE
PocketNet / Bastyon logo

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.gui#220]
In the latest version there's still the "old" pocketnet logo instead of the new Bastyon logo.

**Comment by reignmen** [comment]
Its a logo man, its not that hard to change

**Comment by Dylan-86** [comment]
I know, if I want to change it in my personal distribution, I'd do. I'm speaking about the official app, and I don't have the original logo files from Bastyon. But it's not that normal to have the Pocketnet logo inside the Bastyon app, don't you think?

**Comment by shpingalet007** [comment]
As I see, this issue is irrelevant now
