### ISSUE TITLE
Can't Close the Notification Drop down in Desktop app 

### ISSUE THREAD

**Issue by Srinivasan95D** [pocketnetteam/pocketnet.gui#25]
I had just signed up and opened the notifications bell and i couldn't close it, How can i share any log reports so that you can debug this more efficiently. i know the picture won't be enough.

![notifications_bug](https://user-images.githubusercontent.com/31366055/105017676-0f05be80-5a6a-11eb-878a-8acb9d370c81.png)

**Comment by shpingalet007** [comment]
Very old issue. Already resolved.
