### ISSUE TITLE
Blockchain Problem

### ISSUE THREAD

**Issue by andysavage** [pocketnetteam/pocketnet.gui#284]
On 2021-11-28 20:17:44 I sent this transaction
https://bastyon.com/blockexplorer/transaction/0d6b19c9722688d8980a2110ac30104b3bec820efab9615ab370e7105802ffe7
To my wallet on bastyon/pocketnet
It has still not appeared in my balance, I have checked the address and it is correct. I checked with the source and it says sent, and the transaction ID link doesn't return an error, the page loads but is permanently showing a spinning icon implying waiting for the server to complete the request.

Please tell me what is going on
Thanks

**Comment by andysavage** [comment]
Is anyone taking any notice of this? I would have thought errors in pocketcoin's blockchain would be of interest to the devs.

**Comment by andyoknen** [comment]
@andysavage I don't see this transaction on the network. There could be several situations in which the transaction did not get into the blockchain. In any case, the coins sent remained at the source address.

**Comment by andysavage** [comment]
Ok thanks
