### ISSUE TITLE
Popup window to make a new post

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.gui#29]
Can we get a popup window to make a new post in the app? 

When scrolling through hundreds of new posts, our only option now is that link which scrolls to the top of all posts to make a new post. Instead can we have a button called "New post" which does a popup window to make a new post, so we don't lose our place in the stream trying to play catch up? 

Thanks for all your hard work!

**Comment by shpingalet007** [comment]
Already released. Closing this
