### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#296]
While what is there is what some would say proper English, it doesn't make as much sense as something more understandable

D:\pocketnet.gui-master>grep -r -i "You can enter less than 5 tags" *
-localization/en.js:____loclib.e13162 = "You can enter less than 5 tags"
+localization/en.js:____loclib.e13162 = "You can only enter up to 5 tags"

**Comment by kevinj2016** [comment]
Proper English is, "You can enter fewer than 5 tags." Fewer is the right word because 'tag' is a countable noun. This statement means you can enter 1-4 tags; you cannot enter 5 tags.

Proper English for entering 5 or fewer tags is, "You can enter a maximum of 5 tags."

**Comment by the-real-vortex-v** [comment]
"You can enter 5 tags or less."
"You can enter no more than 5 tags."
"Ye can verily recount no greater than 5 tags here."

All of these are fine.
