### ISSUE TITLE
Node support localization

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.gui#306]
Your node - ?

Synchronization - ?
Status - Статус
Version - Версия
Chain - Блокчейн ?
Height - Высота
Block Hash - Хэш Блока

Wallet - Кошелек
Balance - Баланс
Control - Управление ?
Deposit - ?
Withdraw - ?
Save Wallet - Сохранить Кошелек ?

Configuration - Конфигурация
Enabled - ?
Daemon Path - ?
Data Path - ?
Update Node - Обновить Ноду ?

Node Installing - ?
Node Removing - ?
Node was not found. Download and Install it - ?

System Requirements - ?
50Gb free disk space (SSD drive to ensure speed) - ?
Node control is not yet available for your operating system - ?

Your device already has <%-app.meta.fullname%> Node - ?
You can set system pathes or stop it and install via <%-app.meta.fullname%> Desktop Application - ?
Refresh - ?

No Updates Available - ?
Delete Daemon - ?
Delete Daemon and Data - ?

Node can't staking. Top up balance or wait for 60 blocks to activate coins. - ?

Active - ?
Description - Описание

Your wallet saved to "PATH" - ?
Do you really want to set Bastyon Node Path to Default path? - ?

Less than an hour left - Осталось меньше часа
Left 28 hour(s) - ?

**Comment by Dennis-Volk** [comment]
Your node - Ваш узел

Synchronization - Синхронизация
Status - Статус
Version - Версия
Chain - Блокчейн 
Height - Высота
Block Hash - Хэш Блока

Wallet - Кошелек
Balance - Баланс
Control - Управление ?
Deposit - Внести
Withdraw - Вывести
Save Wallet - Сохранить Кошелек 

Configuration - Конфигурация
Enabled - Включено
Daemon Path - Путь к папке узла
Data Path - Путь к папке данных
Update Node - Обновить Узел

Node Installing - Узел устанавливается
Node is Deleting - Узел удаляется
Node was not found. Download and Install it - Узел не найден. Скачайте и установите его.

System Requirements - Системные Требования
50Gb free disk space (SSD drive to ensure speed) - 50 ГБ свободного дискового пространства (SSD)
Node control is not yet available for your operating system - Управление узлом недоступно для вашей операционной системы

Your device already has <%-app.meta.fullname%> Node - На вашем устройстве уже установлен узел
You can set system path or stop it and install via <%-app.meta.fullname%> Desktop Application - Вы можете установить путь установки или остановите и скачайте узел через компьютерное приложение <%-app.meta.fullname%>
Refresh - Обновить

No Updates Available - Нет доступных обновлений
Delete Node - Удалить узел
Delete Node and Data - Удалить узел и данные

Node can't stake now. Add at least 50 PKOIN or wait for 60 minutes to activate coins. - Узел не может cейчас выигрывать койны через стейкинг. Добавьте минимум 50 Покеткойнов и подожите 60 минут.

Node is Active - Узел Активен
Description - Описание

Your wallet saved to "PATH" - Ваш кошелёк сохранён в следующей папке
Do you really want to set Bastyon Node Path to Default path -  Определить каталог узла по умолчания

Less than an hour left - Осталось меньше часа
Left 28 hour(s) - Осталось менее 28 часов

**Comment by Dennis-Volk** [comment]
28 hour(s) remaining - Осталось менее 28 часов
