### ISSUE TITLE
Visible version

### ISSUE THREAD

**Issue by SnowflakeCrusher** [pocketnetteam/pocketnet.gui#307]
I talked about this in the DevChat briefly. But can we add a visible "version" of the application in an "About" or "Help" section somewhere within the app. I have a bunch of versions of the GUI app spread across my system due to the different ways the app has been installed over the last year. I tried to make a shortcut, but i'm never sure if I'm running the latest binary unless I launch it and look at the path of the binary.

Perhaps in the future this can be a place to show for "automatic version" checks to see if there is a more up to date binary.

**Comment by andyoknen** [comment]
@SnowflakeCrusher Under the account avatar of the "Help Center" - the version is displayed at the top right

**Comment by SnowflakeCrusher** [comment]
Ah, I had my chat up most of the time so I definitely missed that. Thanks for pointing that out.
