### ISSUE TITLE
Please add information in account settings ...

### ISSUE THREAD

**Issue by flyhippo** [pocketnetteam/pocketnet.gui#324]
1. Please add information about the video upload date and publication date in the my videos section, you can place below the statistics on views, comments and stars ...

![image](https://user-images.githubusercontent.com/13536656/149958731-e954cf58-7565-49eb-b5e4-ae433ddb7857.png)

2. And also, please add to the reputation section how many times valid top accounts have been marked

**Comment by shpingalet007** [comment]
Looks like it was resolved. If there is still work needed, please consider reopening it.
