### ISSUE TITLE
App Node Detached with Undefined Error

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#327]
Ryzen 3700X - 16 GB 3200 RAM - Win 11 - nVME - 1GB LAN & WAN

- downloaded the node database from within the app, it unpacked - screen went dark and came back but I'm running nicehash on this machine so that doesn't surprise me -  came back to this and it's been over 5 hours - my core node will sync with the chain in less than 3 hours over 3 weeks behind from a checkpoint. Just wondering if this is normal :
![bastyon_node](https://user-images.githubusercontent.com/50458374/150046083-2252dbf6-094d-45a3-a866-2a552c09ea15.jpg)

**Comment by andyoknen** [comment]
@graebeerd Are you running the node separately from the Bastion app? Such an error usually indicates that the node is started from the outside and the data for connecting (login /password) to the node does not match in the application and the node.

**Comment by graebeerd** [comment]
@andyoknen  This is the GUI, v0.4.119 and the node that is included with it. I have, on the same LAN but a different computer, a core node v0.20.17 running. Oh, and it's Win 10, not 11 - Sorry.

I don't see any way to access it other than the enable/disable link and it doesn't work - it just sits there trying to to start. I'm logged into the app but was never given an opportunity to log into its node. 

I see that the included node is setup in the same default directories as the core node 

Would you suggest removing and reinstalling?

**Comment by andyoknen** [comment]
@graebeerd I would take a look at the node logs
By default in Windows - C:\Users\<YOUR_USERNAME>\appdata\Roaming\Pocketnet\pocketcoin\debug.log

**Comment by graebeerd** [comment]
hmmm...that file does not exist.

**Comment by andyoknen** [comment]
If there is no file, then the node did not start. Could you check the task manager if there is a process pocketcoind.exe ?

**Comment by graebeerd** [comment]
It's not running...when I try to start it via cmd it does create the debug.log file with the following information

2022-01-21T14:40:13Z Pocketnet Core version v0.20.17.0-a64bd50 (release build)
2022-01-21T14:40:13Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2022-01-21T14:40:13Z Assuming ancestors of block 61276732ac5226282d46937b3a4609ed06e98f6621a68941c649ac507dd143bc have valid signatures.
2022-01-21T14:40:13Z Setting nMinimumChainWork=00000000000000000000000000000000000000000000002e9b7b6eb4a23574f0
2022-01-21T14:40:13Z Using the 'shani(1way,2way)' SHA256 implementation
2022-01-21T14:40:13Z Using RdRand as an additional entropy source
2022-01-21T14:40:13Z Default data directory C:\Users\wicke\AppData\Roaming\Pocketcoin
2022-01-21T14:40:13Z Using data directory C:\Users\wicke\AppData\Roaming\Pocketcoin
2022-01-21T14:40:13Z Config file: C:\Users\wicke\AppData\Roaming\Pocketcoin\pocketcoin.conf (not found, skipping)
2022-01-21T14:40:13Z Using at most 125 automatic connections (2048 file descriptors available)
2022-01-21T14:40:13Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2022-01-21T14:40:13Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2022-01-21T14:40:13Z Using 16 threads for script verification
2022-01-21T14:40:13Z init message: Loading Pocket DB...
2022-01-21T14:40:13Z SQLite usage version: 3037000
2022-01-21T14:40:13Z scheduler thread start
2022-01-21T14:40:13Z ErrorLogCallback: 283; Message: recovered 135 frames from WAL file C:\Users\wicke\AppData\Roaming\Pocketcoin\pocketdb\main.sqlite3-wal
2022-01-21T14:40:13Z Creating Sqlite database `main.sqlite3` structure..
2022-01-21T14:40:13Z Creating Sqlite database `web.sqlite3` structure..
2022-01-21T14:40:13Z Checkpoint DB C:\Users\wicke\AppData\Roaming\Pocketcoin\checkpoints\main.sqlite3 not found!
Download actual DB file from https://github.com/pocketnetteam/pocketnet.core/tree/master/checkpoints/main.sqlite3 and place to C:\Users\wicke\AppData\Roaming\Pocketcoin\checkpoints directory.
2022-01-21T14:40:13Z Error: Unable to start server. Checkpoints DB not found. See debug log for details.
2022-01-21T14:40:13Z Shutdown: In progress...

There is a Checkpoints directory in C:\Users\wicke\AppData\Roaming\Pocketnet\pocketcoin but not in C:\Users\wicke\AppData\Roaming\Pocketcoin

**Comment by graebeerd** [comment]
as the debug.log instructs, I did paste a cope of the main.sqlite DB along with the checkpoints directory that it reside in, into ...Roaming\Pocketcoin\ and started pocketcoind again and it's running and connected to the seeded servers.

**Comment by andyoknen** [comment]
What other files are in C:\Users\wicke\AppData\Roaming\Pocketnet\pocketcoin ?

**Comment by graebeerd** [comment]
![pocknet_dir](https://user-images.githubusercontent.com/50458374/150577955-bec12636-1426-4476-b5cf-1192c1d75290.png)

**Comment by andyoknen** [comment]
I would also take a look at the %localappdata%\Programs\Pocketnet\data\setting file

**Comment by graebeerd** [comment]
Here it is, do you see anything out of sorts?

{"server":{"enabled":false,"dontCache":false,"captcha":true,"host":"","iplimiter":{"interval":30000,"count":500,"blacklistcount":3},"ports":{"https":8899,"wss":8099},"ssl":{"name":"Default","key":"cert/key.pem","cert":"cert/cert.pem","passphrase":"password"}},"firebase":{"key":"","id":""},"wallet":{"addresses":{"registration":{"privatekey":"","amount":0.0002,"outs":10,"check":"ipAndUniqAddress"}}},"node":{"enabled":false,"binPath":"C:\\Users\\wicke\\AppData\\Local\\Programs\\Pocketnet\\pocketcoind","ndataPath":"","dataPath":""},"admins":[],"proxies":{"explore":true},"testkeys":[],"systemnotify":{"token":"","chatid":"","parameters":{}},"nedbkey":"settings","_id":"tPWa3ZM9dI0CpgIv"}
{"$$deleted":true,"_id":"tPWa3ZM9dI0CpgIv"}
{"server":{"enabled":false,"dontCache":false,"captcha":true,"host":"","iplimiter":{"interval":30000,"count":500,"blacklistcount":3},"ports":{"https":8899,"wss":8099},"ssl":{"name":"Default","key":"cert/key.pem","cert":"cert/cert.pem","passphrase":"password"}},"firebase":{"key":"","id":""},"wallet":{"addresses":{"registration":{"privatekey":"","amount":0.0002,"outs":10,"check":"ipAndUniqAddress"}}},"node":{"enabled":false,"binPath":"C:\\Users\\wicke\\AppData\\Local\\Programs\\Pocketnet\\pocketcoind","ndataPath":"","dataPath":""},"admins":[],"proxies":{"explore":true},"testkeys":[],"systemnotify":{"token":"","chatid":"","parameters":{}},"nedbkey":"settings","_id":"wqCOfRQJOwyQrtof"}

**Comment by andyoknen** [comment]
Try set data path in app to C:\Users\wicke\AppData\Roaming\Pocketnet\pocketcoin and start node

**Comment by andyoknen** [comment]
Judging by the settings file, the path is used by default, but it's better to check it and specify it explicitly. And once again make sure through the task manager that you do not have another node running. Find process with executable name is pocketcoind.exe

**Comment by graebeerd** [comment]
I can' change anything in the app as the image at the top of this thread remains the same. I changed the datapath in the stetting file and restarted the app, nothing changed. There was no node running and when I manually start the node it shows only the one instance in the taskmanager.

At this point, instead of wasting resources, would it just be better to uninstall and reinstall?

**Comment by andyoknen** [comment]
Why can't you change the path in the app? When the node is stopped in the application, two "Default" buttons appear to change directories, click on the second one to specify the path to the data directory

**Comment by graebeerd** [comment]
They don't show up whether the node is stopped or not. I've tried starting the app with the node not running, starting it with the node running, starting it after I've started the node but no matter what I do, all I get is the same as the image at the top of this thread.

**Comment by andyoknen** [comment]
Do you always have the Enabled section in the loading state? Do the yes/no buttons appear there?

**Comment by graebeerd** [comment]
Sorry for the late reply - Yes, always in the loading state, there are no buttons available.

**Comment by andyoknen** [comment]
OK, I'll try to reproduce this behavior and understand where the error is.

**Comment by andyoknen** [comment]
https://github.com/pocketnetteam/pocketnet.gui/releases/tag/v0.5.0-beta1

**Comment by graebeerd** [comment]
worked and updated today to the rc. Thanks to and for all
