### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.gui#336]
- Renaming the installer
- Renaming an application shortcut
- Fixes in the node management mechanism
- Update Electron to version 16.0
- Implemented a mechanism for changing the scale: `CTRL-` `CTRL+` or over Settings page
- Fixes in saved video feed

**Comment by only1question** [comment]
Need to rename in the context menu:
![image](https://user-images.githubusercontent.com/11753842/151167437-ad86fdf6-2a45-44bb-8908-6b9ad186fac2.png)

**Comment by only1question** [comment]
On Mac App an empty white screen when you press the "Help center".
<img width="494" alt="image" src="https://user-images.githubusercontent.com/11753842/151168220-b27f425c-d807-450f-9b55-6d311e203d41.png">

**Comment by MoloToB** [comment]
Test issue: https://github.com/pocketnetteam/pocketnet.gui/issues/337

Will be updated over time.

**Comment by MoloToB** [comment]
Of the critical problems, only the inability to make a donation through a comment. Medium problem: some browsers cannot record video from the camera or do not open the camera at all. Not all notification sounds play on desktop browsers.
In my opinion, this should have been resolved before release. At least a critical bug.

**Comment by andyoknen** [comment]
> Of the critical problems, only the inability to make a donation through a comment. Medium problem: some browsers cannot record video from the camera or do not open the camera at all. Not all notification sounds play on desktop browsers.
> 
> In my opinion, this should have been resolved before release. At least a critical bug.

These problems do not apply to the node. Please describe these problems in pocketnetteam/pocketnet.gui

**Comment by shpingalet007** [comment]
@andyoknen, I suppose we can close this?
