### ISSUE TITLE
Testing v.0.5.1

### ISSUE THREAD

**Issue by MoloToB** [pocketnetteam/pocketnet.gui#337]
Version
---
0.5.1-beta1

Domain
---
- [x] test.pocketnet.app
- [x] Bastyon Desktop application

Actions
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [ ] Walk through overall interface

> Buttons "Help Center", "F.A.Q.", "Roadmap", "Node Setup", "Applications" leads to white screen.

- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post.
- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Chrome desktop

Actions (in progress)
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [ ] Notifications. New commentary

> Notification comes but without sound

- [ ] Notifications. Answer for commentary

> Notification comes but without sound

- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post.
- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Brave desktop

Actions (in progress)
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [ ] Notifications. New commentary

> Notification comes but without sound

- [ ] Notifications. Answer for commentary

> Notification comes but without sound

- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post.
- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Firefox desktop

Actions
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [ ] Notifications. New post

> Notification comes but without sound

- [ ] Notifications. New commentary

> Notification comes but without sound

- [ ] Notifications. Answer for commentary

> Notification comes but without sound

- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post.
- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Pale Moon desktop

Actions
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [ ] Notifications. Answer for commentary

> Notification comes but without sound

- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post.
- [ ] Open chat. Start conversation with a user

> Entire chat module is missing

- [ ] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Opera desktop

Actions
===

- [x] Open https://bastyon.com / https://test.pocketnet.app (depends of required testing environment)
- [x] Push at commentary text field/grades that must open registration windows.
- [x] Finish registration procedure, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [ ] Notifications. New post
- [ ] Notifications. New commentary

> Notification comes but without sound

- [ ] Notifications. Answer for commentary

> Notification comes but without sound

- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Donate with commentary under post
- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] bastyon.com
- [x] Bastyon android application

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> When user set up avatar image, he can't сhoose camera.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video

> When trying to upload a new video, it does not offer to open the camera

- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Chrome (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Opera (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Firefox (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> When user set up avatar image, he can't dhoose camera.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video

> When trying to upload a new video, it does not offer to open the camera

- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Kiwi browser (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video

> The user is not given the option to open the camera for video recording. Only for photo shots. 

- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Mint browser (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> When using the camera, the picture taken is not set to the profile avatar

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video

> The user is not given the option to open the camera for video recording. Only for photo shots. 

- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Samsung browser (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video

> The user is not given the option to open the camera for video recording. Only for photo shots. 

- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] DuckDuckGo (Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Yandex browser(Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Edge browser(Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Vivaldi browser(Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

Domain
---
- [x] test.pocketnet.app
- [x] Vivaldi browser(Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key
- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users
- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture
- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

**Comment by MoloToB** [comment]
Domain
---
- [x] test.pocketnet.app
- [x] Yandex browser(Android)

Actions
===

- [x] Run application and push registration button
- [x] Finish registration procedure, accept terms and conditions, choose some tags, save account key

> If the user takes an avatar photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Walk through overall interface
- [x] Choose one of a post, write commentary under it
- [x] Choose a different post, give it maximum grade
- [x] Choose a third post, give it minimum grade
- [x] Subscribe to any user
- [x] With search function search for post
- [x] With search function search for users

> Users can only be found in the drop-down menu of the search bar. When you click on the "enter" button, there are no users in the search results

- [x] Choose tag category, compare chosen tag with displayed under posts
- [x] Create your own category with your own name and tags
- [x] Create a test post with picture

> If the user takes a post photo vertically, the horizontal photo "laying on its side" will be displayed.

- [x] Do repost
- [x] Notifications. New post
- [x] Notifications. New commentary
- [x] Notifications. Answer for commentary
- [x] Play some video (from Bastyon servers)
- [x] Play some video (built-in player for Youtube-ish)
- [x] Go to "My Videos". Upload short video
- [ ] Donate with commentary under post

> After entering the donation amount, you cannot continue and make a transaction

- [x] Open chat. Start conversation with a user
- [x] Chat. Create public and private groups
- [x] Go to profile. View user's subscriptions
- [x] In the profile, the "share" button. Create profile link
- [x] Unfollow user
- [x] Donate to user
- [x] Log-out

**Comment by shpingalet007** [comment]
@andyoknen, can we already close this?
