### ISSUE TITLE
Cannot scroll anymore since 0.5.8

### ISSUE THREAD

**Issue by DutchPete** [pocketnetteam/pocketnet.gui#358]
Hey guys, changing the UI and UX is great, but if it prevents me from srcolling it is not so great. When I try to  scroll the only thing that changes is the font size.

I am on MacOS, Mojave 10.14.6.

**Comment by Shpingalet007** [comment]
Hi, @DutchPete. I see. Did you change UI scaling using hotkeys before the issue happened?

**Comment by Shpingalet007** [comment]
@DutchPete, hotfix is on course. Our team will test the solution and pull it as soon as possible.

By the way, you already can test it [on my fork](https://github.com/Shpingalet007/pocketnet.gui/tree/hotfix358-scroll-block). Would be appreciated for your feedback.

**Comment by DutchPete** [comment]
@Shpingalet007 please excuse my ignorance, but how do I test your fork?
I clicked on the link you gave me, then downloaded the zip file from the green Code button.
When I unzipped it, there is a list of files and folders: which one(s) should I use and how?

**Comment by Shpingalet007** [comment]
@DutchPete, to check it, you need to have Node.JS >= 14 platform installed. Then in terminal you need to run next commands.
```
cd FOLDER_WITH_PROJECT
npm install
npm run minimize:bastyon
npm run start
```
Anyway, I think this hotfix could be applied tomorrow or on the next days.

**Comment by DutchPete** [comment]
Iused to have node.js installed but found it a PITA with Homebrew updates so uninstalled it. I just downloaded the latest release and the issue is gone - many thanks to you and the team 👍

**Comment by shpingalet007** [comment]
Okay, marking this as solved for now.

_Fixed with https://github.com/pocketnetteam/pocketnet.gui/pull/360_

**Comment by DutchPete** [comment]
Yes, this is solved.
