### ISSUE TITLE
BUGS version 0.5.8 - Ubuntu

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.gui#361]
Hi,
Ubuntu 21.10
Bastyon 0.5.8

It doesn't load.
It connects to Electron and switching to other nodes is not solving the issue.
No posts, no videos, no chat. Endless loading.

In addition, if you 
`top`
in terminal, this is what you get: 
![image](https://user-images.githubusercontent.com/58813956/156223194-a0982daf-bb29-4783-800b-201d7b940e12.png)

The appname is not Bastyon nor Pocketnet.

**Comment by shpingalet007** [comment]
Interesting. Looks like this bug is _related with https://github.com/pocketnetteam/pocketnet.gui/issues/414_. And again only on Linux... We will look into this
