### ISSUE TITLE
Blank screen instead of working app in Linux version

### ISSUE THREAD

**Issue by yashrk** [pocketnetteam/pocketnet.gui#369]
Version v0.5.8 from the Debian package on Ubuntu 21.10, x86-64.
Version v0.5.8 from the source code on Manjaro, aarch64.

No app in the Bastyon window, only the blank screen.

**Comment by StarSkank** [comment]
Having same issue after installing the updated version (latest release)

**Comment by shpingalet007** [comment]
As I know, it is fixed now. Closing this at this moment
