### ISSUE TITLE
Linux binary shows as "${productName}"

### ISSUE THREAD

**Issue by SnowflakeCrusher** [pocketnetteam/pocketnet.gui#414]
When looking at any process list (ps, top, or any task manager) on the machine where the GUI is installed the name is shown as ${productName}. 

This also shows up as a tooltip when you mouse over the icon in the status tray where it states "${productName} icon".

I've noticed this in Debian Testing with XFCE4 4.16.0.

**Comment by shpingalet007** [comment]
Related to https://github.com/pocketnetteam/pocketnet.gui/issues/345, https://github.com/pocketnetteam/pocketnet.gui/issues/361

**Comment by shpingalet007** [comment]
Looks like it was resolved. Feel free to reopen if occurs again.
