### ISSUE TITLE
Invite to comment after user liked the post

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#463]
## What needs to be done
When a user liked the post and starred it, service need to ask him if he would like to leave a comment about the post. Developer might use example made on other social network.

![Example of invite-to-comment](https://user-images.githubusercontent.com/22795961/170949576-2e3af49c-a060-4674-8768-e1de05f4c221.png)

**Comment by the-real-vortex-v** [comment]
... "and share as your page". What is this supposed to mean? 
"and share your page". I think you should change it to.

**Comment by shpingalet007** [comment]
Dark theme is not made on this pull. Need to be done

![No dark theme image](https://user-images.githubusercontent.com/22795961/173389337-4f1aaf81-bf3f-492e-80db-efa8a02473db.png)

**Comment by shpingalet007** [comment]
@Traler

**Comment by shpingalet007** [comment]
Banner is not showing on [bastyon.com](https://bastyon.com/). Feature works with issues.

**Comment by shpingalet007** [comment]
There are errors that need to be resolved

**Comment by Traler** [comment]
I will do
