### ISSUE TITLE
Language change produce only partial translation on some pages

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#497]
## Description
On some pages, after the user switched languages, UI is translated only partially. Reloading page helps btw.

#### Confirmed on next pages
- Profile ➜ Wallet
- Profile ➜ Settings

## How to reproduce
1. Go to the page from the list
2. Go to the bottom of website
3. Change the language
4. Now you can see that some strings weren't translated

**Comment by j-bitmaker** [comment]
Fixed. Please, test
