### ISSUE TITLE
QR code image deleted from pocketnet EXE dir when I updated to 0.0.14.

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.gui#5]
* Windows 10 with Pocketnet app v0.0.14.

I downloaded and installed the Windows pocketnet app 0.0.13. Then I signed up using the app, and saved my qr code as an image in the EXE directory. Then within 10 minutes the app updated itself (with my permission), now my qr code image is gone.

Is it possible to get another QR image? Is it possible to not delete all files in the EXE dir so it doesn't delete my notes or QR code image? 

Thanks! I'm a programmer. Really great product, very well polished!

**Comment by bulrush15** [comment]
So how do I make another QR code image to save on my PC?

**Comment by pocketnetteam** [comment]
Thanks for your feedback.

You can view your QR code and save it again in Profile -> Manage -> Accounts. To the right of the account click on the key icon.

**Comment by bulrush15** [comment]
Woohoo! Thanks!
