### ISSUE TITLE
Can't send PKOIN comment twice

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#507]
## What needs to be done
User can't send twice PKOIN-comment. Something is going wrong there.

If you open the PKOIN-commenting UI immediately after the first made, then it will show balance as 0.

## How to reproduce
1. Find 1-st post and PKOIN-comment it.
2. Find 2-nd post and PKOIN-comment it.
3. You'll see one of the next errors
   - **Zero balance error** - Happens when UI opened called again without user await (seconds).
   - **Network error** - Happens if you try to send 2-nd PKOIN-comment without page refresh.
   - **Too long loading** - Happens if you try to send 2-nd PKOIN-comment without page refresh. The comment would not be sent anyway.

**Comment by j-bitmaker** [comment]
Fixed. Please, test
