### ISSUE TITLE
Cyrillic private key not working

### ISSUE THREAD

**Issue by Akaidar01** [pocketnetteam/pocketnet.gui#537]
When you try to enter with a Russian mnemonic phrase, it gives an erro
![Снимок экрана 2022-06-30 171631](https://user-images.githubusercontent.com/90545016/176664306-7b2ef0be-6cea-492a-bf55-85cbb0638b01.png)
r

**Comment by Akaidar01** [comment]
DevTools failed to load source map: Could not load content for https://bastyon.com/js/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by shpingalet007** [comment]
@Akaidar01, please don't post issues in **Github issues** if they are not related to released versions. Pre-release bugs and issues must be reported directly in the associated pull request as a comment.

_Related to #446_. @grish2018, take a look.

**Comment by shpingalet007** [comment]
This is not issue as #499 is deployed on only on prerelease 6. Closing.
