### ISSUE TITLE
EasyNode installation error

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.gui#539]
The problem is most likely due to the changed transport

#### Exception happens here: `request.on is not a function`
https://github.com/pocketnetteam/pocketnet.gui/blob/3e935c27e54c5b4e0b1101baecb2d478013c81bf/proxy16/node/control.js#L533-L536

#### `.on` on line 207 is not a function
https://github.com/pocketnetteam/pocketnet.gui/blob/3e935c27e54c5b4e0b1101baecb2d478013c81bf/proxy16/node/applications.js#L202-L227

**Comment by shpingalet007** [comment]
Looks like this issue happens due to missing await before proceeding with request object.
It returns **`Promise<Request>`** instead of **`Request`**.

Sandboxed the code and tried to make request after awaiting. Looks like it works. Pushing a pull request with changes, it may close this issue.

**Comment by shpingalet007** [comment]
While issue looks to be resolved, there is RAM overflow on binary download. Need to be resolved. May affect other parts of Tor transport too... @cenitelas, what do you think?

**Comment by shpingalet007** [comment]
Pull #584 removes Tor from node download process. Could be fixed in future pulls.
