### ISSUE TITLE
"Undefined Connection Error"

### ISSUE THREAD

**Issue by Interprises** [pocketnetteam/pocketnet.gui#54]
Receiving "Undefined connection error" issued by Pocketnet.app when posting or trying to star a post. The error (see attached) appears momentarily at the bottom right of the app, Can't post or star a post. Happens for me when logged in on various devices and IPs. Have cleared cache/data and reinstalled app yet problem persists. Thanks in advance for any help.

![2021-04-01_13-13-30](https://user-images.githubusercontent.com/78180549/113336870-9a15f700-92ec-11eb-9b22-5620b0fb06cd.jpg)

**Comment by andyoknen** [comment]
Bug fixed. Please change profile info - any changes and save.

**Comment by Interprises** [comment]
Did as you suggested, Andy. Can confirm the issue is resolved. Much appreciated!
