### ISSUE TITLE
LocalStorage desynchronization between tabs/windows

### ISSUE THREAD

**Issue by Akaidar01** [pocketnetteam/pocketnet.gui#543]
![image](https://user-images.githubusercontent.com/90545016/176926871-b636c2ef-8257-4cdb-808d-0440e7caee86.png)
![image](https://user-images.githubusercontent.com/90545016/176926963-acdfd4b3-fc60-4fa3-b6fb-1114d63e2ead.png)

**Comment by shpingalet007** [comment]
Okay, after some investigations, looks like this topic already covered by browser API's. For example we read about it here [here] (https://medium.com/@mfreundlich1/syncing-localstorage-across-multiple-tabs-cb5d0b1feaab).

**Comment by shpingalet007** [comment]
The issue is not just the described thing by @Akaidar01. It is too about everything between tabs not synchronized. At this moment, tabs/windows opened before changes can't be observed without page update.
