### ISSUE TITLE
Failed to fetch error in videos cabinet

### ISSUE THREAD

**Issue by bRostovtsev** [pocketnetteam/pocketnet.gui#562]
error when opening video cabinet in profile
![Screenshot_10](https://user-images.githubusercontent.com/101694688/178653876-b0d26622-03af-498e-90a1-846b7d619522.png)

**Comment by shpingalet007** [comment]
When a user has videos on old peertube servers that are already offline, fetch would not be able to get data. This happens in the video cabinet. Omitting errors that are related to offline peertube servers.
