### ISSUE TITLE
Translate the Top Posts into the Discussed in the feed

### ISSUE THREAD

**Issue by MoMentalochka** [pocketnetteam/pocketnet.gui#573]

**Comment by MoMentalochka** [comment]
getmostcommentedfeed
topHeight           (int)
topContentHash      (string, optional)
countOut            (int, optional)
lang                (string, optional)
tags                (vector<string>, optional)
contentTypes        (vector<int>, optional)
txIdsExcluded       (vector<string>, optional)
adrsExcluded        (vector<string>, optional)
tagsExcluded        (vector<string>, optional)
address             (string, optional)
depth               (int, optional)

**Comment by MoMentalochka** [comment]
Ready for testing, the nodes are updated, but need to wait for the proxy update.

**Comment by MoMentalochka** [comment]
update
wait until the load capacity is tested

**Comment by MoMentalochka** [comment]
#582

**Comment by shpingalet007** [comment]
Still not merged, so let's keep it open

**Comment by only1question** [comment]
@MoMentalochka The maximum depth on node is limited to 1 month.

**Comment by shpingalet007** [comment]
Completed on #623
