### ISSUE TITLE
Android will not update, package is invalid 

### ISSUE THREAD

**Issue by jkaldon** [pocketnetteam/pocketnet.gui#585]
I think these screenshots speak for themselves.  I have tried deleting the app and installing from the downloaded apk, but it produces the same result. 

Thanks, 
\- Joshua 

<img width="200px" src="https://user-images.githubusercontent.com/1554651/180615884-a71d242a-05d4-444f-bb3a-227ee7184d7b.png"/> <img width="200px" src="https://user-images.githubusercontent.com/1554651/180615886-e1729dc0-ba7d-49db-872f-7f4eb87df229.png" /> <img width="200px" src="https://user-images.githubusercontent.com/1554651/180615888-841cfc04-5e63-4f93-ac62-19ed9a50eb8b.png" />

**Comment by shpingalet007** [comment]
@jkaldon, does it happen on 0.8.7 or 0.8.8? It can be that it happens on both... Send please Android version here too. Thanks

**Comment by shpingalet007** [comment]
Okay, @jkaldon, looks like I resolved the issue. Can you [install again 0.8.8](https://github.com/pocketnetteam/pocketnet.gui/releases/tag/v0.8.8) and say if it goes? App wasn't aligned well after built.

**Comment by shpingalet007** [comment]
> Okay, @jkaldon, looks like I resolved the issue. Can you [install again 0.8.8](https://github.com/pocketnetteam/pocketnet.gui/releases/tag/v0.8.8) and say if it goes? App wasn't aligned well after built.

I think I resolved it here. Check it

**Comment by shpingalet007** [comment]
Okay, made some changes. Could you look if it solves the problem now?

**Comment by jkaldon** [comment]
It works now.  Thank you and feel free to reach out if you need any other testing.
