### ISSUE TITLE
Incorrect text's

### ISSUE THREAD

**Issue by MoMentalochka** [pocketnetteam/pocketnet.gui#606]
![Screenshot_20220808_080632](https://user-images.githubusercontent.com/56727108/183343699-6348690a-0b5a-4d4e-a8f6-a9e7a9952730.jpg)
![Screenshot_20220808_080617](https://user-images.githubusercontent.com/56727108/183343704-51f067ca-1d21-49d6-93ab-b518bb9f75df.jpg)

**Comment by only1question** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/11753842/183405252-eca5f7b4-fde3-4139-a0e1-a0da6bcf7bca.png">

**Comment by only1question** [comment]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/11753842/183407540-d657c2f2-7a7e-419b-9f23-619236f0ee3c.png">

**Comment by MoMentalochka** [comment]
#610
