### ISSUE TITLE
Node List column size

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.gui#615]
Could you enlarge the first column, because part of the node name is lost

![image](https://user-images.githubusercontent.com/24531527/184164605-906f378a-39b6-4f14-a5ec-ae2245ed2772.png)

**Comment by shpingalet007** [comment]
@andyoknen okay, done in #696. Already deployed on PRE. Look if it is nice 😺

**Comment by andyoknen** [comment]
> @andyoknen okay, done in #696. Already deployed on PRE. Look if it is nice 😺

It looks great!
