### ISSUE TITLE
Realize building apps process in GitHub Actions

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.gui#630]
All builded binaries saved to https://dev.pocketnet.app/binaries/
The header of the commit on which the build was made is fixed in the file `head.txt`

- [X] Production
- [ ] Testing

**Comment by andyoknen** [comment]
@shpingalet007 Will you help to implement the assembly of test binaries?

**Comment by shpingalet007** [comment]
@andyoknen of course 👍
