### ISSUE TITLE
Bug: Animated GIFs get cut off midway.

### ISSUE THREAD

**Issue by j-bitmaker** [pocketnetteam/pocketnet.gui#649]
Animated GIFs get cut off midway.  Also, the server doesn't seem to support PNG.

**Comment by shpingalet007** [comment]
@j-bitmaker, in what state is this issue?

**Comment by KempfCreative** [comment]
This no longer appears to be an issue. I was able to upload both a PNG and animated GIF. The PNG worked, and the GIF was showing the full frame count.

**Comment by shpingalet007** [comment]
@KempfCreative, thank you! It was expected, but anyway it is nice to hear feedback about this issue. Closing for now.
