### ISSUE TITLE
Bugs: boost and pkoin comment

### ISSUE THREAD

**Issue by j-bitmaker** [pocketnetteam/pocketnet.gui#651]
- [x] Mobile design problems
- [x] Single post isn't clicable
- [x] Long post problems

**Comment by j-bitmaker** [comment]
Added fixes in #648

**Comment by shpingalet007** [comment]
PR #648 resolves this issue. However, the PR was merged invalidly, so it doesn't state as merged. Feel free to reopen if there are any problems
