### ISSUE TITLE
v0.8.22 - Node Status Shows Only 'Requesting' - Never Shows Wallet Amount

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#756]
### Describe the bug

Window 10, Bastyon version 0.8.22
Started Bastyon GUI executable and waited for at least 20 hours 

While viewing the Node status -Under Wallet - Status stuck on 'Requesting' - Balance shows 0.00000000 PKOIN - Addressing getstakinginfo in a CMD window works and shows NSW and Balance.

see attached screen shots.

### Steps to reproduce

Start the Bastyon Windows GUI

### Expected behavior

Should fill in Status and Balance

### Screenshots and recordings

![Status-Requestiong](https://user-images.githubusercontent.com/50458374/201474223-cc80aee3-671a-4697-bb6e-2393f1cc69d4.png)
![wallet-client-return](https://user-images.githubusercontent.com/50458374/201474409-79f1ea01-dfcc-48f0-addc-721c9aae42d7.jpg)

### OS / Linux distribution

Windows 10

### Version

v0.8.22

### Type application

Desktop

**Comment by graebeerd** [comment]
Can't explain why but issue cleared itself today. Closing issue

**Comment by shpingalet007** [comment]
I think we could keep this issue updated. @andyoknen, as specialist in nodes, can you make some suggestions about what can produce such bug? This information would be sent to someone to debug that. Thanks!
