### ISSUE TITLE
feat: christmas design for chat

### ISSUE THREAD

**Issue by j-bitmaker** [pocketnetteam/pocketnet.gui#816]
- christmas key icon (lollypop)
- chrismas chat icon

**Comment by j-bitmaker** [comment]
This PR closes #817

**Comment by shpingalet007** [comment]
This PR is a continuation of #774.

**Comment by shpingalet007** [comment]
Closing this as duplicate. Read reason [here](https://github.com/pocketnetteam/pocketnet.gui/issues/774#issuecomment-1348501233). Proceed in #774.
